# Generated by Django 4.1.3 on 2022-12-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machete', '0002_productimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
